import type { SkillPath } from "@/types/career-path";

// Mock data; replace with API calls when the paths endpoint exists.
export const SKILL_PATHS: SkillPath[] = [
  {
    slug: "git-version-control",
    title: "Git & Version Control",
    description: "Master branching, merging, and collaborative workflows",
    courseCount: 2,
    weekCount: 3,
    icon: "git",
    href: "/learning-path/skill/git-version-control",
  },
  {
    slug: "api-design-basics",
    title: "API Design Basics",
    description: "Design clean, consistent REST endpoints",
    courseCount: 2,
    weekCount: 4,
    icon: "api",
    href: "/learning-path/skill/api-design-basics",
  },
  {
    slug: "sql-fundamentals",
    title: "SQL Fundamentals",
    description: "Query, join, and shape relational data confidently",
    courseCount: 3,
    weekCount: 5,
    icon: "sql",
    href: "/learning-path/skill/sql-fundamentals",
  },
  {
    slug: "command-line-essentials",
    title: "Command Line Essentials",
    description: "Navigate and automate from the terminal",
    courseCount: 1,
    weekCount: 2,
    icon: "cli",
    href: "/learning-path/skill/command-line-essentials",
  },
  {
    slug: "docker-basics",
    title: "Docker Basics",
    description: "Containerize and ship applications reliably",
    courseCount: 2,
    weekCount: 4,
    icon: "docker",
    href: "/learning-path/skill/docker-basics",
  },
  {
    slug: "data-visualization",
    title: "Data Visualization",
    description: "Turn numbers into charts people actually read",
    courseCount: 2,
    weekCount: 3,
    icon: "data-viz",
    href: "/learning-path/skill/data-visualization",
  },
  {
    slug: "testing-fundamentals",
    title: "Testing Fundamentals",
    description: "Write tests that catch real bugs",
    courseCount: 2,
    weekCount: 4,
    icon: "testing",
    href: "/learning-path/skill/testing-fundamentals",
  },
  {
    slug: "authentication-security-basics",
    title: "Authentication & Security Basics",
    description: "Implement login flows and protect user data",
    courseCount: 2,
    weekCount: 3,
    icon: "security",
    href: "/learning-path/skill/authentication-security-basics",
  },
];